version: '3.8'

networks:
  otel_net:
    external: true

services:
  goldrush-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goldrush-integration
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - otel_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    env_file:
      - .env
    networks:
      - otel_net

  promtail-goldrush-integration:
    image: grafana/promtail:2.8.2
    container_name: promtail-goldrush-integration
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./config/promtail-config.yml:/etc/promtail/config.yml
    command:
      - "-config.file=/etc/promtail/config.yml"
    networks:
      - otel_net

volumes:
  redis-data: