server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://otel-lgtm:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: goldrush_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: goldrush_logs
          __path__: /app/logs/app.log