name: GITHUB-ACTIONS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  GO_VERSION: 1.23.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Run tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Build Docker image
      run: docker build -t goldrush-integration .

    - name: Run Docker Compose tests
      run: |
        docker-compose up -d
        docker-compose ps
        docker-compose down